package presentacion;

import java.awt.*;

import javax.swing.*;
import javax.swing.border.*;
import javax.swing.plaf.basic.*;
import java.awt.event.*;
import java.util.Properties;

import presentacion.propiedadesVentana.*;
import presentacion.ventanaMenuSniffer.MenuSniffer;
import servicioAccesoDatos.FachadaFicheroDirectorios;

/**
 * Panel que informa sobre la aplicación, sus autores y memoria usada y
 * disponible para su ejecución.
 * 
 * @author Leonardo García & JoseRamón Gutierrez & Carlos Mardones Muga
 * @version 3.0
 * 
 * @see javax.swing.JDialog
 */
public class VentanaAcercaDe extends JDialog {
	/**
	 * Genera una nueva ventana que contiene datos sobre la aplicación.
	 * 
	 * see #inicializacionComponentes()
	 * 
	 * @see presentacion.propiedadesVentana.CentrarVentana
	 */
	public VentanaAcercaDe() {
		super(MenuSniffer.getFrames()[0], "Acerca de Sniffer II", true);
		initComponents();
		setSize(328, 400);
		this.setResizable(false);

		new CentrarVentana(this);
		addWindowListener(new AdaptadorVentana());

		show();
	}//VentanaAcercaDe

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Código Generado ">
	private void initComponents() {
		jButton1 = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jButton2 = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();

		Runtime runtime = Runtime.getRuntime();
		runtime.gc();
		long totalMemory = runtime.totalMemory();
		long usedMemory = (totalMemory - runtime.freeMemory()) / 1024;
		long maxMemory = runtime.maxMemory() / 1024;

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setAlwaysOnTop(true);
		setResizable(false);
		jButton1.setIcon(new javax.swing.ImageIcon(
				FachadaFicheroDirectorios.getdirectorioData("DIR_IMAGES") + 
				System.getProperty("file.separator") + 
				"sniffer.gif"));
		jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dispose();
			}
		});
		jPanel1.setBorder(javax.swing.BorderFactory
				.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
		jButton2.setIcon(new javax.swing.ImageIcon(
				FachadaFicheroDirectorios.getdirectorioData("DIR_IMAGES") + 
				System.getProperty("file.separator") + 
				"escudo1.gif"));
		jButton2.setBorderPainted(false);
		jButton2.setContentAreaFilled(false);
		jButton2.setFocusPainted(false);
		jButton2.setFocusable(false);

		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jButton2,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel2Layout.createSequentialGroup().addContainerGap().add(
						jButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE).addContainerGap()));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Sniffer II");

		jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12));
		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel2.setText("para la creaci\u00f3n de un");

		jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12));
		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel3.setText("conjunto de datos");

		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabel4.setText("Versi\u00f3n 1.7");

		org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel3Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jPanel3Layout
																		.createSequentialGroup()
																		.add(
																				jPanel3Layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								jLabel1,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.add(
																								org.jdesktop.layout.GroupLayout.TRAILING,
																								jLabel2,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								150,
																								Short.MAX_VALUE)
																						.add(
																								jLabel3,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								150,
																								Short.MAX_VALUE))
																		.addContainerGap())
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																jLabel4))));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel3Layout.createSequentialGroup().addContainerGap().add(
						jLabel1).add(14, 14, 14).add(jLabel2).addPreferredGap(
						org.jdesktop.layout.LayoutStyle.RELATED).add(jLabel3)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED, 14,
								Short.MAX_VALUE).add(jLabel4)));

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel1Layout.createSequentialGroup().addContainerGap().add(
						jPanel2,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED, 24,
								Short.MAX_VALUE).add(jPanel3,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jPanel2,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				11,
																				11,
																				11)
																		.add(
																				jPanel3,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))
										.addContainerGap()));

		jPanel4.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));
		jLabel5.setText("Tutor: ");

		jLabel6.setText("Jose Manuel S\u00e1iz");

		jLabel7.setText("Autores:");

		jLabel8.setText("Carlos Mardones Muga");

		jLabel9.setText("");

		org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel4Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jLabel7)
														.add(
																jPanel4Layout
																		.createSequentialGroup()
																		.add(
																				jLabel5)
																		.add(
																				jPanel4Layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								jPanel4Layout
																										.createSequentialGroup()
																										.add(
																												19,
																												19,
																												19)
																										.add(
																												jPanel4Layout
																														.createParallelGroup(
																																org.jdesktop.layout.GroupLayout.LEADING)
																														.add(
																																jLabel8)
																														.add(
																																jLabel9)))
																						.add(
																								jPanel4Layout
																										.createSequentialGroup()
																										.add(
																												29,
																												29,
																												29)
																										.add(
																												jLabel6)))))
										.addContainerGap(106, Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel4Layout.createSequentialGroup().addContainerGap().add(
						jPanel4Layout.createParallelGroup(
								org.jdesktop.layout.GroupLayout.BASELINE).add(
								jLabel5).add(jLabel6)).addPreferredGap(
						org.jdesktop.layout.LayoutStyle.RELATED).add(jLabel7)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED).add(
								jLabel8).addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED).add(
								jLabel9).addContainerGap(
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		jLabel10.setText("Memoria Usada:");

		jLabel11.setText("Memoria Máxima:");

		jLabel12.setText("" + usedMemory + " Kb");

		jLabel13.setText("" + maxMemory + " Kb");

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(19, 19, 19)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.TRAILING)
														.add(
																org.jdesktop.layout.GroupLayout.LEADING,
																jPanel1,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.add(
																org.jdesktop.layout.GroupLayout.LEADING,
																jPanel4,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												jLabel11)
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												jLabel13,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												56,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												jLabel10)
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												jLabel12,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												70,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				59,
																				Short.MAX_VALUE)
																		.add(
																				jButton1)
																		.add(
																				15,
																				15,
																				15)))
										.add(363, 363, 363)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												154,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel4,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(16, 16, 16)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.BASELINE)
																						.add(
																								jLabel10)
																						.add(
																								jLabel12,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								22,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.BASELINE)
																						.add(
																								jLabel11)
																						.add(
																								jLabel13,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								20,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
														.add(jButton1))
										.addContainerGap(138, Short.MAX_VALUE)));
		pack();
	}// </editor-fold>

	//(ComandoIniciarSalirAplicacion)jButton1
	private class AdaptadorVentana extends WindowAdapter {
		/**
		 * Cierra la ventana
		 * 
		 * @param e
		 *            evento asociado
		 */
		public void windowClosing(WindowEvent e) {
			dispose();
		}
	}//AdaptadorVentana

	/**
	 * Oyente encargado de cerrar la ventana.
	 * 
	 * @see java.awt.event.ActionListener
	 */
	private class OyenteCerrar implements ActionListener {
		/**
		 * Acción que se realiza.
		 * 
		 * @param e
		 *            evento que llama al oyente
		 */
		public void actionPerformed(ActionEvent e) {
			dispose();
		}//actionPerformed
	}//OyenteCerrar

	// Declaración de varibales -no modificar
	private javax.swing.JButton jButton1;

	private javax.swing.JButton jButton2;

	private javax.swing.JLabel jLabel1;

	private javax.swing.JLabel jLabel10;

	private javax.swing.JLabel jLabel11;

	private javax.swing.JLabel jLabel12;

	private javax.swing.JLabel jLabel13;

	private javax.swing.JLabel jLabel2;

	private javax.swing.JLabel jLabel3;

	private javax.swing.JLabel jLabel4;

	private javax.swing.JLabel jLabel5;

	private javax.swing.JLabel jLabel6;

	private javax.swing.JLabel jLabel7;

	private javax.swing.JLabel jLabel8;

	private javax.swing.JLabel jLabel9;

	private javax.swing.JPanel jPanel1;

	private javax.swing.JPanel jPanel2;

	private javax.swing.JPanel jPanel3;

	private javax.swing.JPanel jPanel4;
	// Fin de declaración de variables
}//Clase VentanaAcercaDe
