package presentacion.preferencias;

import java.awt.event.*;
import java.util.*;
import presentacion.Mediador;
import presentacion.comandos.*;
import presentacion.propiedadesVentana.CentrarVentana;
import presentacion.ventanaMenuSniffer.MenuSniffer;
/**
 * Ventana donde nos permite generar los script para windows y unix para
 * las capturas, exportaciones, y capturas desde fichero.
 * 
 * @author Leonardo García & JoseRamón Gutierrez
 * @version 2.0
 * 
 * @see javax.swing.JDialog
 */
public class PreferenciasGenerarBat extends javax.swing.JDialog {
	
	/**
	 * Receptor del comando.
	 * 
	 * @see presentacion.Mediador
	 */
	Mediador mediador;
	/**
	 * Comando encargado de abrir la ventana de ficehro.
	 * 
	 * @see presentacion.comandos.Comando
	 * @see presentacion.comandos.CBAbrirFichero
	 */
	private Comando jButton1; //CBAbrirFichero Preferencias;
	/**
	 * Comando encargado de abrir la ventana guardar ficehro.
	 * 
	 * @see presentacion.comandos.Comando
	 * @see presentacion.comandos.CBGuardarFichero
	 */
	private Comando jButton2; //CBGuardarFichero .bat
	/**
	 * Comando encargado de acpetar la captura.
	 * 
	 * @see presentacion.comandos.Comando
	 * @see presentacion.comandos.CBAceptar
	 */
	private Comando jButton3; //CBAceptar
    
	/**
	 *  Constructor de la clase por defecto
	 */
    public PreferenciasGenerarBat() {
    	super(MenuSniffer.getFrames()[0], "Generar Script", true);
		mediador = new Mediador();
        initComponents();
		this.setResizable(false);
		new CentrarVentana(this);
		this.setVisible(true);
    }
    

	/**
	 * Contructor de la clase que le estableces el receptro del comando 
	 * 
	 * @param med receptor
	 */
    public PreferenciasGenerarBat(Mediador med) {
    	super(MenuSniffer.getFrames()[0], "Generar Script", true);
		mediador = med;
        initComponents();
		this.setResizable(false);
		new CentrarVentana(this);
		this.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">                          
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonScan = new javax.swing.JRadioButton();
        jRadioButtonExport = new javax.swing.JRadioButton();
        jRadioButtonFromFile = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        //jButton1 = new javax.swing.JButton();
        jButton1 = new CBAbrirFichero(mediador, "GenerarBatPreferencias");
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        //jButton2 = new javax.swing.JButton();
        jButton2 = new CBGuardarFichero(mediador, "GenerarBatBat");
        jButtonCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButtonPorDefecto = new javax.swing.JRadioButton();
        jRadioButtonDefUsuario = new javax.swing.JRadioButton();
        jTextFieldMegas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        //jButton3 = new javax.swing.JButton();
        jButton3 = new CBAceptar(mediador, "GenerarScript");
        
        jRadioButtonWindows = new javax.swing.JRadioButton();
        jRadioButtonUnix = new javax.swing.JRadioButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));
        buttonGroup1.add(jRadioButtonScan);
        jRadioButtonScan.setMnemonic('c');
        jRadioButtonScan.setSelected(true);
        jRadioButtonScan.setText("captura");
        jRadioButtonScan.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonScan.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButtonScan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonScanItemStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButtonExport);
        jRadioButtonExport.setMnemonic('e');
        jRadioButtonExport.setText("exporta");
        jRadioButtonExport.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        //jRadioButtonExport.setEnabled(false);
        jRadioButtonExport.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButtonExport.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonExportItemStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButtonFromFile);
        jRadioButtonFromFile.setMnemonic('d');
        jRadioButtonFromFile.setText("desde fichero");
        jRadioButtonFromFile.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        //jRadioButtonFromFile.setEnabled(false);
        jRadioButtonFromFile.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(26, 26, 26)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jRadioButtonFromFile)
                    .add(jRadioButtonExport)
                    .add(jRadioButtonScan))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jRadioButtonScan)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRadioButtonExport)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRadioButtonFromFile)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jLabel1.setText("Preferencias: ");

        //jButton1.setText("..");
        

        jLabel2.setText("Script:");

        //jButton2.setText("..");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add((CBGuardarFichero)jButton2)
                    .add((CBAbrirFichero)jButton1)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add((CBAbrirFichero)jButton1)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 19, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add((CBGuardarFichero)jButton2))
                .add(20, 20, 20))
        );

        jPanel2.getAccessibleContext().setAccessibleName("Datos");

        
        
        
        
        
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Memoria MVJ"));
        buttonGroup3.add(jRadioButtonPorDefecto);
        jRadioButtonPorDefecto.setMnemonic('p');
        jRadioButtonPorDefecto.setSelected(true);
        jRadioButtonPorDefecto.setText("... por defecto");
        jRadioButtonPorDefecto.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonPorDefecto.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup3.add(jRadioButtonDefUsuario);
        jRadioButtonDefUsuario.setMnemonic('f');
        jRadioButtonDefUsuario.setText("... definido usuario");
        jRadioButtonDefUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonDefUsuario.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButtonDefUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonDefUsuarioItemStateChanged(evt);
            }
        });

        jTextFieldMegas.setText("200");
        jTextFieldMegas.setEnabled(false);

        jLabel3.setText("megas");
        jLabel3.setEnabled(false);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jRadioButtonPorDefecto)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(17, 17, 17)
                        .add(jTextFieldMegas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel3))
                    .add(jRadioButtonDefUsuario))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jRadioButtonPorDefecto)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRadioButtonDefUsuario)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel3)
                    .add(jTextFieldMegas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );



        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("S.O."));
        buttonGroup2.add(jRadioButtonWindows);
        jRadioButtonWindows.setMnemonic('w');
        jRadioButtonWindows.setSelected(true);
        jRadioButtonWindows.setText("Windows");
        jRadioButtonWindows.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonWindows.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButtonWindows.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
              //  jRadioButtonWindowsItemStateChanged(evt);
            }
        });


        buttonGroup2.add(jRadioButtonUnix);
        jRadioButtonUnix.setMnemonic('u');
        jRadioButtonUnix.setText("Unix");
        jRadioButtonUnix.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonUnix.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButtonUnix.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonUnixItemStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(26, 26, 26)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jRadioButtonUnix)
                    .add(jRadioButtonWindows))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jRadioButtonWindows)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRadioButtonUnix)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4.getAccessibleContext().setAccessibleName("S.O.");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jButtonCancelar)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add((CBAceptar)jButton3)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3, 0, 109, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 56, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add((CBAceptar)jButton3)
                            .add(jButtonCancelar))
                        .add(19, 19, 19))
                    .add(layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        
        
        
        
        
        
        
        
        
        
        
        
        
        
/*        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Memoria MVJ"));
        buttonGroup3.add(jRadioButtonPorDefecto);
        jRadioButtonPorDefecto.setMnemonic('d');
        jRadioButtonPorDefecto.setSelected(true);
        jRadioButtonPorDefecto.setText("... por defecto");
        jRadioButtonPorDefecto.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonPorDefecto.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup3.add(jRadioButtonDefUsuario);
        jRadioButtonDefUsuario.setMnemonic('u');
        jRadioButtonDefUsuario.setText("... definido usuario");
        jRadioButtonDefUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonDefUsuario.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButtonDefUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonDefUsuarioItemStateChanged(evt);
            }
        });

        jTextFieldMegas.setText("200");
        jTextFieldMegas.setEnabled(false);

        jLabel3.setText("megas");
        jLabel3.setEnabled(false);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(17, 17, 17)
                        .add(jTextFieldMegas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel3))
                    .add(jRadioButtonDefUsuario)
                    .add(jRadioButtonPorDefecto))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jRadioButtonPorDefecto)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRadioButtonDefUsuario)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldMegas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jButtonCancelar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add((CBAceptar)jButton3)
                        .add(4, 4, 4))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jPanel3, 0, 109, Short.MAX_VALUE)
                        .add(22, 22, 22)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jButtonCancelar)
                            .add((CBAceptar)jButton3)))
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        */
        pack();
    }// </editor-fold>                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
// TODO: Agrege su codigo aqui:
        this.dispose();
    }                                        

    private void jRadioButtonDefUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {                                                        
        if (evt.getStateChange() == ItemEvent.SELECTED) {
                jTextFieldMegas.setEnabled(true);
                jLabel3.setEnabled(true);
        } else {
                jTextFieldMegas.setEnabled(false);
                jLabel3.setEnabled(false);
        }
    }         
    private void jRadioButtonUnixItemStateChanged(java.awt.event.ItemEvent evt) {                                                        
//   	 TODO: Agrege su codigo aqui:
    }   
    
    private void jRadioButtonWindowsActionPerformed(java.awt.event.ItemEvent evt) {                                                  
//    	 TODO: Agrege su codigo aqui:
    	    }                                                 


    private void jRadioButtonScanItemStateChanged(java.awt.event.ItemEvent evt) {                                                  
// TODO: Agrege su codigo aqui:
    }                                                 

    private void jRadioButtonExportItemStateChanged(java.awt.event.ItemEvent evt) {                                                    

    }                                                   

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                                
// TODO: Agrege su codigo aqui:
        this.dispose();
    }                                               
    
	public static void setFicheroPref(String aux) {
		jTextField1.setText(aux);
	}
	
	public static String getFicheroPref(){
		return jTextField1.getText();
	}
    
	public static void setFicheroBat(String aux) {
		jTextField2.setText(aux);
	}
	
	public static String getFicheroBat(){
		return jTextField2.getText();
	}
	
	public static String getTipo(){
		String aux ="";
        for (Enumeration e=buttonGroup1.getElements(); e.hasMoreElements(); ) {
        	javax.swing.JRadioButton b = (javax.swing.JRadioButton)e.nextElement();
            if (b.getModel() == buttonGroup1.getSelection()) {
            	aux = b.getText();
            }
        }
        return aux;
	}
    
	public static String getSO(){
		String aux ="";
        for (Enumeration e=buttonGroup2.getElements(); e.hasMoreElements(); ) {
        	javax.swing.JRadioButton b = (javax.swing.JRadioButton)e.nextElement();
            if (b.getModel() == buttonGroup2.getSelection()) {
            	aux = b.getText();
            }
        }
        return aux;
	}
	
	public static String getMvM(){
		String aux;
		if (jRadioButtonPorDefecto.isSelected()) aux ="-1";
		else aux= jTextFieldMegas.getText();
		return aux;
	}
    // Declaración de varibales -no modificar                     
    private static javax.swing.ButtonGroup buttonGroup1;
    private static javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    //private javax.swing.JButton jButton1;
    //private javax.swing.JButton jButton2;
    //private javax.swing.JButton jButton3;
    private javax.swing.JRadioButton jRadioButtonUnix;
    private javax.swing.JRadioButton jRadioButtonWindows;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonDefUsuario;
    private javax.swing.JRadioButton jRadioButtonExport;
    private javax.swing.JRadioButton jRadioButtonFromFile;
    private static javax.swing.JRadioButton jRadioButtonPorDefecto;
    private javax.swing.JRadioButton jRadioButtonScan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private static javax.swing.JTextField jTextField1;
    private static javax.swing.JTextField jTextField2;
    private static javax.swing.JTextField jTextFieldMegas;
    // Fin de declaración de variables                   
    
}