package presentacion.preferencias;

import presentacion.Mediador;
import presentacion.comandos.*;
import presentacion.propiedadesVentana.CentrarVentana;
import presentacion.ventanaMenuSniffer.MenuSniffer;

/**
 * Configuracion de los ficheros por defecto del programa
 * 
 * @author Leonardo García & JoseRamón Gutierrez
 * @version 2.0
 * 
 * @see javax.swing.JDialog
 */
public class PreferenciasConfiguracion extends javax.swing.JDialog {
	/**
	 * Receptor del comando.
	 * 
	 * @see presentacion.Mediador
	 */
	Mediador mediador;
	/**
	 * Comando encargado de acpetar la carpeta capturas.
	 * 
	 * @see presentacion.comandos.Comando
	 * @see presentacion.comandos.CBAbrirCarpeta
	 */
	Comando jButton1; //CBAbrirCarpeta
	/**
	 * Comando encargado de acpetar la carpeta exportación.
	 * 
	 * @see presentacion.comandos.Comando
	 * @see presentacion.comandos.CBAbrirCarpeta
	 */
	Comando jButton2; //CBAbrirCarpeta
	/**
	 * Comando encargado de acpetar la carpeta scripts
	 * 
	 * @see presentacion.comandos.Comando
	 * @see presentacion.comandos.CBAbrirCarpeta
	 */
	Comando jButton3; //CBAbrirCarpeta
	/**
	 * Comando encargado de acpetar la captura carpeta parametrizacion.
	 * 
	 * @see presentacion.comandos.Comando
	 * @see presentacion.comandos.CBAbrirCarpeta
	 */
	Comando jButton4; //CBAbrirCarpeta
	/**
	 * Comando encargado de acpetar la captura.
	 * 
	 * @see presentacion.comandos.Comando
	 * @see presentacion.comandos.CBAbrirCarpeta
	 */
	Comando jButton5; //CBAceptar
	
	
	/**
	 *  Constructor de la clase por defecto
	 */
    public PreferenciasConfiguracion() {
		super(MenuSniffer.getFrames()[0], "Configuracion", true);
		mediador = new Mediador();
		initComponents();
		this.setResizable(false);
		new CentrarVentana(this);
    }
    
	/**
	 * Contructor de la clase que le estableces el receptro del comando 
	 * 
	 * @param med receptor
	 */
    public PreferenciasConfiguracion(Mediador med) {
		super(MenuSniffer.getFrames()[0], "Configuración....", true);
		mediador = med;
        initComponents();
		this.setResizable(false);
		new CentrarVentana(this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sniffer II - Directorios de Usuario"));
        jLabel1.setText("Capturas:");

        jLabel2.setText("Exportaciones: ");

        jLabel3.setText("Scripts:");

        jLabel4.setText("Parametrización:");


        jButton1=new CBAbrirCarpeta(mediador,"Capturas");
        jButton2=new CBAbrirCarpeta(mediador,"Exportaciones");
        jButton3=new CBAbrirCarpeta(mediador,"Scripts");
        jButton4=new CBAbrirCarpeta(mediador,"Paremetrizacion");
        
        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(jLabel3)
                    .add(jLabel2)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jTextField4 ,org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 220, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField3 ,org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 220, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 220, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 220, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add((CBAbrirCarpeta)jButton2, 0, 0, Short.MAX_VALUE)
                    .add((CBAbrirCarpeta)jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, Short.MAX_VALUE)
                    .add((CBAbrirCarpeta)jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, Short.MAX_VALUE)
                    .add((CBAbrirCarpeta)jButton1, 0, 0, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add((CBAbrirCarpeta)jButton1))
                .add(11, 11, 11)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add((CBAbrirCarpeta)jButton2))
                .add(14, 14, 14)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add((CBAbrirCarpeta)jButton3))
                .add(14, 14, 14)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add((CBAbrirCarpeta)jButton4))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        //jButton6.setText("jButton6");
        jButton5 = new CBAceptar(mediador, "AceptarConfiguracion");

        jButton6.setText("Cancelar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jButton6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add((CBAceptar)jButton5))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(21, 21, 21)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add((CBAceptar)jButton5)
                    .add(jButton6))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>
    
    /**
     * Cierra la ventana
     * 
     * @param evt evento
     */
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//    	 TODO: Agrege su codigo aqui:
    	        this.dispose();
    	    } 
   
    /**
     * Establece la ruta de capturas
     * 
     * @param aux ruta
     */
    public static void setCapturas(String aux){
    	jTextField1.setText(aux);
    }
    
    /**
     * Devuelve la ruta de Capturas
     * 
     * @return ruta
     */
    public static String getCapturas(){
    	return jTextField1.getText();
    }
    
    /**
     * Establece la ruta de exportaciones
     * 
     * @param aux ruta
     */
    public static void setExportaciones(String aux){
    	jTextField2.setText(aux);
    }
    
    /**
     * Devuelve la ruta de exportaciones
     * 
     * @return ruta
     */
    public static String getExportaciones(){
    	return jTextField2.getText();
    }
    
    /**
     * Establece la ruta de scripts
     * 
     * @param aux ruta
     */
    public static void setScripts(String aux){
    	jTextField3.setText(aux);
    }
    
    /**
     * Devuelve la ruta de scripts.
     * 
     * @return ruta
     */
    public static String getScripts(){
    	return jTextField3.getText();
    }
    
    /**
     * Establece la ruta de parametrizacion
     * 
     * @param aux ruta
     */
    public static void setParametrizacion(String aux){
    	jTextField4.setText(aux);
    }
    
    /**
     * Devuelve la ruta de parametrizaciones
     * 
     * @return ruta
     */
    public static String getParametrizacion(){
    	return jTextField4.getText();
    }
    

    // Declaración de varibales -no modificar
 //   private javax.swing.JButton jButton1;
 //   private javax.swing.JButton jButton2;
 //   private javax.swing.JButton jButton3;
 //   private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
 //   private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JTextField jTextField1;
    private static javax.swing.JTextField jTextField2;
    private static javax.swing.JTextField jTextField3;
    private static javax.swing.JTextField jTextField4;
    // Fin de declaración de variables
    
}
