package presentacion.preferencias;

import java.awt.event.*;
import presentacion.Mediador;
import presentacion.comandos.*;
import presentacion.propiedadesVentana.CentrarVentana;
import presentacion.ventanaMenuSniffer.MenuSniffer;

/**
 * Ventana donde vemos e introducimos las preferencias de captura desde fichero
 *  y da paso a la captura desde fichero
 * 
 * @author Leonardo García & JoseRamón Gutierrez
 * @version 2.0
 * 
 * @see javax.swing.JDialog
 */
public class PreferenciasFromFile extends javax.swing.JDialog {
	/** * Titulo de la ventana. */
	private String title;
	/** * Lista de protocolos. */
	private String[] Protocolos = { "", "TCP", "UDP", "ICMP", };
	/** * Lista de puertos. */
	private String[] Puertos = { "", "80", "20", "21", "23", "22", "25", "110", };
	/** Lista de capacidad. */
	private String[] Capacidad = { "kilobyte(s)", "megabyte(s)", "gigabyte(s)", };
	/** * Lista de tiempos. */
	private String[] Tiempos = { "segundo(s)", "minuto(s)", "hora(s)",
			"dia(s)", };
	/** * Si es captura o veer las preferencias. */
	private static boolean tipo;
	/** * Lista de dispositivos. */
	private static String[] Dispositivos = { "Seleccione un dispositivo", };
	/** * Lista de dispositivos. */
	private static String[] Dispo;
	
	/**
	 * Comando encargado de abrir la ventana de Ayuda.
	 * 
	 * @see presentacion.comandos.Comando
	 * @see presentacion.comandos.CBFiltroAyuda
	 */
	Comando jButton1; //CBFiltroAyuda;
	/**
	 * Comando encargado de abrir la ventana Abrir fichero.
	 * 
	 * @see presentacion.comandos.Comando
	 * @see presentacion.comandos.CJMAbrirFichero
	 */
	Comando jButton2; //CJMAbrirFichero
	/**
	 * Comando encargado de acpetar la captura.
	 * 
	 * @see presentacion.comandos.Comando
	 * @see presentacion.comandos.CBAceptar
	 */
	Comando jButton3; //CBAceptar
	/**
	 * Comando encargado de abrir la ventana guardar ficehro.
	 * 
	 * @see presentacion.comandos.Comando
	 * @see presentacion.comandos.CBGuardarFichero
	 */
	Comando jButton5; //CBGuardarFichero
	/**
	 * Comando encargado de abrir la ventana de ficehro.
	 * 
	 * @see presentacion.comandos.Comando
	 * @see presentacion.comandos.CBAbrirFichero
	 */
	Comando jButton6; //CBAbrirFichero
	/**
	 * Comando encargado de abrir la ventana de ficehro.
	 * 
	 * @see presentacion.comandos.Comando
	 * @see presentacion.comandos.CBAbrirFichero
	 */
	Comando jButton7; //CJMAbrirFichero

	/**
	 * Receptor del comando.
	 * 
	 * @see presentacion.Mediador
	 */
	Mediador mediador;
	
	
	/**
	 *  Constructor de la clase por defecto
	 */
	public PreferenciasFromFile() {
		super(MenuSniffer.getFrames()[0], "Captura", true);
		title = "Inicio Captura desde fichero";
		tipo = true;
		mediador = new Mediador();
		
		initComponents();
		((CBFiltroAyuda) jButton1).setEnabled(false);
		((CBGuardarFichero) jButton5).setVisible(false);
		((CBAbrirFichero) jButton6).setVisible(false);
		this.setResizable(false);
		new CentrarVentana(this);
	}

	/**
	 * Contructor de la clase que le estableces el receptro del comando 
	 * y si es para captura desde fichero o para mostrar las prpopiedades
	 * 
	 * @param tipo es captura desde fichero
	 * @param med receptor
	 */
	public PreferenciasFromFile(boolean tipo,Mediador med) {
		super(MenuSniffer.getFrames()[0], "Captura", true);
		this.tipo = tipo;
		if (tipo == true)
			title = "Inicio Captura desde fichero";
		else
			title = "Preferencias de Captura desde fichero";
		mediador = med;
		initComponents();
		((CBFiltroAyuda) jButton1).setEnabled(false);
		if (tipo == false) {
			//((CBAceptar) jButton3).setVisible(false);
			jButton4.setVisible(false);
		} else {
			((CBGuardarFichero) jButton5).setVisible(false);
			((CBAbrirFichero) jButton6).setVisible(false);
		}
		this.setResizable(false);
		new CentrarVentana(this);
	}



	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Código Generado ">
	private void initComponents() {

		
		jPanel3 = new javax.swing.JPanel();
		jLabel9 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		jPanel6 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jComboBox2 = new javax.swing.JComboBox();
		jLabel4 = new javax.swing.JLabel();
		jComboBox3 = new javax.swing.JComboBox();
		jPanel7 = new javax.swing.JPanel();
		jCheckBox2 = new javax.swing.JCheckBox();
		jTextField2 = new javax.swing.JTextField();
		//        jButton1 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jCheckBox1 = new javax.swing.JCheckBox();
		jPanel4 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		//        jButton2 = new javax.swing.JButton();
		jCheckBox3 = new javax.swing.JCheckBox();
		jPanel8 = new javax.swing.JPanel();
		jPanel9 = new javax.swing.JPanel();
		jCheckBox4 = new javax.swing.JCheckBox();
		jTextField4 = new javax.swing.JTextField();
		jComboBox4 = new javax.swing.JComboBox();
		jCheckBox5 = new javax.swing.JCheckBox();
		jTextField5 = new javax.swing.JTextField();
		jComboBox5 = new javax.swing.JComboBox();
		jLabel6 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();
		jCheckBox6 = new javax.swing.JCheckBox();
		jTextField7 = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jCheckBox7 = new javax.swing.JCheckBox();
		jPanel5 = new javax.swing.JPanel();
		jCheckBox8 = new javax.swing.JCheckBox();
		jCheckBox9 = new javax.swing.JCheckBox();
		jCheckBox10 = new javax.swing.JCheckBox();
		jTextField8 = new javax.swing.JTextField();
		jTextField9 = new javax.swing.JTextField();
		jTextField10 = new javax.swing.JTextField();
		jTextField11 = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jComboBox6 = new javax.swing.JComboBox();
		jComboBox7 = new javax.swing.JComboBox();
		//        jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		//        jButton5 = new javax.swing.JButton();
		//        jButton6 = new javax.swing.JButton();
		//jButton7 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle(title);
		jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jLabel9.setText("Visualiza mensajes de ayuda de esta pantalla");

		org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel3Layout.createSequentialGroup().addContainerGap().add(
						jLabel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						490, Short.MAX_VALUE).addContainerGap()));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jLabel9));
		getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Captura desde fichero"));
		jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
				"Filtro",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Times New Roman", 0, 11)));
		jLabel2.setText("Host:");

		jTextField1.setText("");

		jLabel3.setText("Protocolo:");

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(Protocolos));

		jLabel4.setText("Puerto:");

		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(Puertos));

		jCheckBox2.setText("Avanzado:");
		jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0,
				0, 0));
		jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
		jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jCheckBox2ItemStateChanged(evt);
			}
		});

		jTextField2.setEnabled(false);

		jButton1 = new CBFiltroAyuda(mediador);

		org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(
				jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel7Layout.createSequentialGroup().addContainerGap().add(
						jCheckBox2).addPreferredGap(
						org.jdesktop.layout.LayoutStyle.RELATED).add(
						jTextField2,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 275,
						Short.MAX_VALUE).add(27, 27, 27).add(
						(CBFiltroAyuda) jButton1).addContainerGap()));
		jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel7Layout.createParallelGroup(
						org.jdesktop.layout.GroupLayout.BASELINE).add(
						jCheckBox2).add(jTextField2,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(
						(CBFiltroAyuda) jButton1)));

		org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout
				.setHorizontalGroup(jPanel6Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel6Layout
										.createSequentialGroup()
										.add(
												jPanel6Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jPanel6Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.add(
																				jLabel2)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jTextField1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				99,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.add(
																				14,
																				14,
																				14)
																		.add(
																				jLabel3)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jComboBox2,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				100,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				22,
																				Short.MAX_VALUE)
																		.add(
																				jLabel4)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jComboBox3,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				100,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(
																jPanel7,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel6Layout
				.setVerticalGroup(jPanel6Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel6Layout
										.createSequentialGroup()
										.add(
												jPanel6Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(
																jTextField1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel2)
														.add(
																jComboBox3,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel4)
														.add(
																jComboBox2,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel3))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												10, Short.MAX_VALUE)
										.add(
												jPanel7,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));

        jLabel1.setText("Fichero:");

        //jButton7.setText("...");
        jButton7 = new CBAbrirFichero(mediador, "Abrir fichero de Capturas desde fichero...");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField11)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add((CBAbrirFichero)jButton7))
                    .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add((CBAbrirFichero)jButton7)
                    .add(jTextField11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        jPanel4.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Fichero/os Capturado/os"));
		jLabel5.setText("Fichero:");

		jButton2 = new CBGuardarFichero(mediador, "Browse...FromFile");

		jCheckBox3.setText("Multiples ficheros");
		jCheckBox3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0,
				0, 0));
		jCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));
		jCheckBox3.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jCheckBox3ItemStateChanged(evt);
			}
		});

		jCheckBox4.setText("Pr\u00f3ximo fichero cada");
		jCheckBox4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0,
				0, 0));
		jCheckBox4.setEnabled(false);
		jCheckBox4.setMargin(new java.awt.Insets(0, 0, 0, 0));
		jCheckBox4.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jCheckBox4ItemStateChanged(evt);
			}
		});

		jTextField4.setEnabled(false);

		jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(Capacidad));
		jComboBox4.setEnabled(false);

		jCheckBox5.setText("Pr\u00f3ximo fichero cada");
		jCheckBox5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0,
				0, 0));
		jCheckBox5.setEnabled(false);
		jCheckBox5.setMargin(new java.awt.Insets(0, 0, 0, 0));
		jCheckBox5.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jCheckBox5ItemStateChanged(evt);
			}
		});

		jTextField5.setEnabled(false);

		jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(Tiempos));
		jComboBox5.setEnabled(false);

		jLabel6.setText("ficheros");
		jLabel6.setEnabled(false);

		jTextField6.setEnabled(false);

		jCheckBox6.setText("Pila de");
		jCheckBox6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0,
				0, 0));
		jCheckBox6.setEnabled(false);
		jCheckBox6.setMargin(new java.awt.Insets(0, 0, 0, 0));
		jCheckBox6.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jCheckBox6ItemStateChanged(evt);
			}
		});

		jTextField7.setEnabled(false);

		jLabel7.setText("ficheros");
		jLabel7.setEnabled(false);

		jCheckBox7.setText("Stop desp\u00faes de");
		jCheckBox7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0,
				0, 0));
		jCheckBox7.setEnabled(false);
		jCheckBox7.setMargin(new java.awt.Insets(0, 0, 0, 0));
		jCheckBox7.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jCheckBox7ItemStateChanged(evt);
			}
		});

		org.jdesktop.layout.GroupLayout jPanel9Layout = new org.jdesktop.layout.GroupLayout(
				jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout
				.setHorizontalGroup(jPanel9Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel9Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel9Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jCheckBox7).add(
																jCheckBox6)
														.add(jCheckBox5).add(
																jCheckBox4))
										.add(10, 10, 10)
										.add(
												jPanel9Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jTextField6,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																65,
																Short.MAX_VALUE)
														.add(
																jTextField7,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																65,
																Short.MAX_VALUE)
														.add(
																jTextField5,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																65,
																Short.MAX_VALUE)
														.add(
																jTextField4,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																65,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel9Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jLabel7)
														.add(jLabel6)
														.add(
																jPanel9Layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.LEADING,
																				false)
																		.add(
																				jComboBox5,
																				0,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.add(
																				jComboBox4,
																				0,
																				86,
																				Short.MAX_VALUE)))
										.add(25, 25, 25)));
		jPanel9Layout
				.setVerticalGroup(jPanel9Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel9Layout
										.createSequentialGroup()
										.add(
												jPanel9Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(
																jComboBox4,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jCheckBox4)
														.add(
																jTextField4,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel9Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jCheckBox5)
														.add(
																jComboBox5,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																jTextField5,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel9Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jCheckBox6)
														.add(jLabel6)
														.add(
																jTextField6,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.add(
												jPanel9Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jCheckBox7)
														.add(jLabel7)
														.add(
																jTextField7,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))));

		org.jdesktop.layout.GroupLayout jPanel8Layout = new org.jdesktop.layout.GroupLayout(
				jPanel8);
		jPanel8.setLayout(jPanel8Layout);
		jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel8Layout.createSequentialGroup().add(45, 45, 45).add(
						jPanel9,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(94, Short.MAX_VALUE)));
		jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel9,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE));

		org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel4Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING,
																false)
														.add(
																jPanel4Layout
																		.createSequentialGroup()
																		.add(
																				jLabel5)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jTextField3,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				390,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				(CBGuardarFichero) jButton2))
														.add(jCheckBox3)
														.add(
																jPanel8,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap(
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel4Layout.createSequentialGroup().add(
						jPanel4Layout.createParallelGroup(
								org.jdesktop.layout.GroupLayout.BASELINE).add(
								jTextField3,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(jLabel5).add((CBGuardarFichero) jButton2))
						.add(10, 10, 10).add(jCheckBox3).addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED).add(
								jPanel8,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		jPanel5.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Parar Captura"));
		jCheckBox8.setText("despu\u00e9s de ...");
		jCheckBox8.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0,
				0, 0));
		jCheckBox8.setMargin(new java.awt.Insets(0, 0, 0, 0));
		jCheckBox8.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jCheckBox8ItemStateChanged(evt);
			}
		});

		jCheckBox9.setText("despues de ...");
		jCheckBox9.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0,
				0, 0));
		jCheckBox9.setMargin(new java.awt.Insets(0, 0, 0, 0));
		jCheckBox9.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jCheckBox9ItemStateChanged(evt);
			}
		});

		jCheckBox10.setText("despues de ...");
		jCheckBox10.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0,
				0, 0));
		jCheckBox10.setMargin(new java.awt.Insets(0, 0, 0, 0));
		jCheckBox10.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jCheckBox10ItemStateChanged(evt);
			}
		});

		jTextField8.setEnabled(false);

		jTextField9.setEnabled(false);

		jTextField10.setEnabled(false);

		jLabel8.setText("patete/es");
		jLabel8.setEnabled(false);

		jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(Capacidad));
		jComboBox6.setEnabled(false);

		jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(Tiempos));
		jComboBox7.setEnabled(false);

		org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout
				.setHorizontalGroup(jPanel5Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel5Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel5Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jCheckBox8).add(
																jCheckBox9)
														.add(jCheckBox10))
										.add(20, 20, 20)
										.add(
												jPanel5Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING,
																false)
														.add(
																jTextField8,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																65,
																Short.MAX_VALUE)
														.add(jTextField9).add(
																jTextField10))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel5Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jLabel8)
														.add(jComboBox6, 0, 95,
																Short.MAX_VALUE)
														.add(jComboBox7, 0, 95,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel5Layout
				.setVerticalGroup(jPanel5Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel5Layout
										.createSequentialGroup()
										.add(
												jPanel5Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jCheckBox8)
														.add(jLabel8)
														.add(
																jTextField8,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel5Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jCheckBox9)
														.add(
																jTextField9,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																jComboBox6,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel5Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jCheckBox10)
														.add(
																jTextField10,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																jComboBox7,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		
		if (tipo)
			jButton3 = new CBAceptar(mediador, "AceptarInicioCapturaFromFile");
		else
			jButton3 = new CBAceptar(mediador, "Salir");
		jButton4.setText("Cancelar");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton5 = new CBGuardarFichero(mediador, "GuardarInicioCapturaXMLFromFile");

		jButton6 = new CBAbrirFichero(mediador, "AbrirFicheroXMLFromFile");

		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel2Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																jPanel2Layout
																		.createSequentialGroup()
																		.add(
																				jPanel5,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				47,
																				Short.MAX_VALUE)
																		.add(
																				jPanel2Layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.TRAILING,
																								false)
																						.add(
																								(CBAbrirFichero) jButton6,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.add(
																								jButton4,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jPanel2Layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								(CBGuardarFichero) jButton5)
																						.add(
																								(CBAceptar) jButton3)))
														.add(
																jPanel1,
																0,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.add(
																jPanel4,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel4,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(
												jPanel2Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jPanel2Layout
																		.createSequentialGroup()
																		.add(
																				16,
																				16,
																				16)
																		.add(
																				jPanel2Layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.BASELINE)
																						.add(
																								(CBGuardarFichero) jButton5)
																						.add(
																								(CBAbrirFichero) jButton6))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				60,
																				Short.MAX_VALUE)
																		.add(
																				jPanel2Layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.BASELINE)
																						.add(
																								(CBAceptar) jButton3)
																						.add(
																								jButton4))
																		.addContainerGap(
																				22,
																				Short.MAX_VALUE))
														.add(
																jPanel2Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jPanel5,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap()))));
		getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>

	private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {

		if (evt.getStateChange() == ItemEvent.DESELECTED) {
			//Filter_AV = false;
			jTextField2.setEnabled(false);
			((CBFiltroAyuda) jButton1).setEnabled(false);
			jLabel2.setEnabled(true);
			jLabel3.setEnabled(true);
			jLabel4.setEnabled(true);
			jTextField1.setEnabled(true);
			jComboBox2.setEnabled(true);
			jComboBox3.setEnabled(true);
		} else {
			//Filter_AV = true;
			jTextField2.setEnabled(true);
			((CBFiltroAyuda) jButton1).setEnabled(true);
			jLabel2.setEnabled(false);
			jLabel3.setEnabled(false);
			jLabel4.setEnabled(false);
			jTextField1.setEnabled(false);
			jComboBox2.setEnabled(false);
			jComboBox3.setEnabled(false);
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {

		this.dispose();
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {

		// llama a Fcaptura
		// graba los parametros de las preferencias en el Beans
	}

	private void jCheckBox10ItemStateChanged(java.awt.event.ItemEvent evt) {

		if (evt.getStateChange() == ItemEvent.DESELECTED) {
			jCheckBox10ItemState(false);
		} else {
			jCheckBox10ItemState(true);
			jCheckBox9.setSelected(false);
			jCheckBox9ItemState(false);
		}
	}

	private void jCheckBox9ItemStateChanged(java.awt.event.ItemEvent evt) {

		if (evt.getStateChange() == ItemEvent.DESELECTED) {
			jCheckBox9ItemState(false);
		} else {
			jCheckBox9ItemState(true);
			jCheckBox10.setSelected(false);
			jCheckBox10ItemState(false);
		}
	}

	private void jCheckBox8ItemStateChanged(java.awt.event.ItemEvent evt) {

		if (evt.getStateChange() == ItemEvent.DESELECTED) {
			jCheckBox8ItemState(false);
		} else {
			jCheckBox8ItemState(true);
		}
	}

	private void jCheckBox7ItemStateChanged(java.awt.event.ItemEvent evt) {

		if (evt.getStateChange() == ItemEvent.DESELECTED) {
			jCheckBox7ItemState(false);
		} else {
			jCheckBox7ItemState(true);
		}
	}

	private void jCheckBox6ItemStateChanged(java.awt.event.ItemEvent evt) {

		if (evt.getStateChange() == ItemEvent.DESELECTED) {
			jCheckBox6ItemState(false);
		} else {
			jCheckBox6ItemState(true);
		}
	}

	private void jCheckBox5ItemStateChanged(java.awt.event.ItemEvent evt) {

		if (evt.getStateChange() == ItemEvent.DESELECTED) {
			jCheckBox5ItemState(false);
		} else {
			jCheckBox5ItemState(true);
			jCheckBox4.setSelected(false);
			jCheckBox4ItemState(false);
		}
	}

	private void jCheckBox4ItemStateChanged(java.awt.event.ItemEvent evt) {

		if (evt.getStateChange() == ItemEvent.DESELECTED) {
			jCheckBox4ItemState(false);
			jCheckBox4.setSelected(true);
			jCheckBox4ItemState(true);
		} else {
			jCheckBox4ItemState(true);
			jCheckBox5.setSelected(false);
			jCheckBox5ItemState(false);
		}
	}

	private void jCheckBox3ItemStateChanged(java.awt.event.ItemEvent evt) {

		if (evt.getStateChange() == ItemEvent.DESELECTED) {
			jCheckBox3ItemState(false);
		} else {
			jCheckBox3ItemState(true);
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		
	}

	private void jCheckBox3ItemState(boolean auxVar) {
		jCheckBox4.setEnabled(auxVar);
		//jCheckBox5.setEnabled(auxVar);
		jCheckBox6.setEnabled(auxVar);
		jCheckBox7.setEnabled(auxVar);
		if (auxVar == true) {
			jCheckBox4.setSelected(true);
			jCheckBox4ItemState(jCheckBox4.isSelected());
			jCheckBox5ItemState(jCheckBox5.isSelected());
			jCheckBox6ItemState(jCheckBox6.isSelected());
			jCheckBox7ItemState(jCheckBox7.isSelected());
			jCheckBox9.setEnabled(false);
			jCheckBox9ItemState(false);
			jCheckBox10.setEnabled(false);
			jCheckBox10ItemState(false);
		} else {
			jCheckBox4ItemState(false);
			jCheckBox5ItemState(false);
			jCheckBox6ItemState(false);
			jCheckBox7ItemState(false);
			jCheckBox9ItemState(false);
			jCheckBox10ItemState(false);
			//jCheckBox9.setEnabled(true);
			//jCheckBox9ItemState(jCheckBox9.isSelected());
			//jCheckBox10.setEnabled(true);
			//jCheckBox10ItemState(jCheckBox10.isSelected());
		}
	}

	private void jCheckBox4ItemState(boolean auxVar) {
		jTextField4.setEnabled(auxVar);
		//jScrollBar1.setEnabled(auxVar);
		jComboBox4.setEnabled(auxVar);
	}

	private void jCheckBox5ItemState(boolean auxVar) {
		jTextField5.setEnabled(auxVar);
		//jScrollBar2.setEnabled(auxVar);
		jComboBox5.setEnabled(auxVar);
	}

	private void jCheckBox6ItemState(boolean auxVar) {
		jTextField6.setEnabled(auxVar);
		//jScrollBar3.setEnabled(auxVar);
		jLabel6.setEnabled(auxVar);
	}

	private void jCheckBox7ItemState(boolean auxVar) {
		jTextField7.setEnabled(auxVar);
		//jScrollBar4.setEnabled(auxVar);
		jLabel7.setEnabled(auxVar);
	}

	private void jCheckBox8ItemState(boolean auxVar) {
		jTextField8.setEnabled(auxVar);
		//jScrollBar5.setEnabled(auxVar);
		jLabel8.setEnabled(auxVar);
	}

	private void jCheckBox9ItemState(boolean auxVar) {
		jTextField9.setEnabled(auxVar);
		//jScrollBar6.setEnabled(auxVar);
		jComboBox6.setEnabled(auxVar);
	}

	private void jCheckBox10ItemState(boolean auxVar) {
		jTextField10.setEnabled(auxVar);
		//jScrollBar7.setEnabled(auxVar);
		jComboBox7.setEnabled(auxVar);
	}

	public static void setFromFile(String aux){
		jTextField11.setText(aux);
	}
	
	public static String getFromFile(){
		return jTextField11.getText();
	}

	public static void setPromiscuo(boolean aux) {
		jCheckBox1.setSelected(aux);
	}

	public static boolean getPromiscuo() {
		return jCheckBox1.isSelected();
	}

	public static void setHost(String aux) {
		jTextField1.setText(aux);
	}

	public static String getHost() {
		return jTextField1.getText();
	}

	public static void setProtocolo(String aux) {
		for (int i = 0; i < jComboBox2.getItemCount(); i++) {
			if (jComboBox2.getItemAt(i).equals(aux)) {
				jComboBox2.setSelectedIndex(i);
			}
		}
	}

	public static String getProtocolo() {
		return (String) jComboBox2.getSelectedItem();
	}

	public static void setPuerto(String aux) {
		for (int i = 0; i < jComboBox3.getItemCount(); i++) {
			if (jComboBox3.getItemAt(i).equals(aux)) {
				jComboBox3.setSelectedIndex(i);
			}
		}
	}

	public static String getPuerto() {
		return (String) jComboBox3.getSelectedItem();
	}

	public static void setAvanzado(boolean aux) {
		jCheckBox2.setSelected(aux);
	}

	public static boolean getAvanzado() {
		return jCheckBox2.isSelected();
	}

	public static void setAvanzado(String aux) {
		jTextField2.setText(aux);
	}

	public static String getAvanzadoDato() {
		return jTextField2.getText();
	}

	public static void setFichero(String aux) {
		jTextField3.setText(aux);
	}

	public static String getFichero() {
		return jTextField3.getText();
	}

	public static void setMultiplesFicheros(boolean aux) {
		if (aux == false)
			jCheckBox3.setSelected(true);
		jCheckBox3.setSelected(aux);
	}

	public static boolean getMultiplesFicheros() {
		return jCheckBox3.isSelected();
	}

	public static void setProximoEspacio(boolean aux) {
		jCheckBox4.setSelected(aux);
	}

	public static boolean getProximoEspacio() {
		return jCheckBox4.isSelected();
	}

	public static void setProximoEspacio(String aux) {
		jTextField4.setText(aux);
	}

	public static String getProximoEspacioDato() {
		return jTextField4.getText();
	}

	public static void setProximoEspacioTipo(String aux) {
		String ooo;
		for (int i = 0; i < jComboBox4.getItemCount(); i++) {
			ooo = jComboBox4.getItemAt(i).toString();
			if (jComboBox4.getItemAt(i).toString().contains(aux.toLowerCase())) {
				jComboBox4.setSelectedIndex(i);
			}
		}
	}

	public static String getProximoEspacioTipo() {
		return (String) jComboBox4.getSelectedItem();
	}

	public static void setProximoTiempo(boolean aux) {
		jCheckBox5.setSelected(aux);
	}

	public static boolean getProximoTiempo() {
		return jCheckBox5.isSelected();
	}

	public static void setProximoTiempo(String aux) {
		jTextField5.setText(aux);
	}

	public static String getProximoTiempoDato() {
		return jTextField5.getText();
	}

	public static void setProximoTiempoTipo(String aux) {
		String ooo;
		for (int i = 0; i < jComboBox5.getItemCount(); i++) {
			ooo = jComboBox5.getItemAt(i).toString();
			if (jComboBox5.getItemAt(i).toString().contains(aux.toLowerCase())) {
				jComboBox5.setSelectedIndex(i);
			}
		}
	}

	public static String getProximoTiempoTipo() {
		return (String) jComboBox5.getSelectedItem();
	}

	public static void setPila(boolean aux) {
		jCheckBox6.setSelected(aux);
	}

	public static boolean getPila() {
		return jCheckBox6.isSelected();
	}

	public static void setPila(String aux) {
		jTextField6.setText(aux);
	}

	public static String getPilaDato() {
		return jTextField6.getText();
	}

	public static void setStop(boolean aux) {
		jCheckBox7.setSelected(aux);
	}

	public static boolean getStop() {
		return jCheckBox7.isSelected();
	}

	public static void setStop(String aux) {
		jTextField7.setText(aux);
	}

	public static String getStopDato() {
		return jTextField7.getText();
	}

	public static void setDespuesPaquetes(boolean aux) {
		jCheckBox8.setSelected(aux);
	}

	public static boolean getDespuesPaquetes() {
		return jCheckBox8.isSelected();
	}

	public static void setDespuesPaquetes(String aux) {
		jTextField8.setText(aux);
	}

	public static String getDespuesPaquetesDato() {
		return jTextField8.getText();
	}

	public static void setDespuesEspacio(boolean aux) {
		jCheckBox9.setSelected(aux);
	}

	public static boolean getDespuesEspacio() {
		return jCheckBox9.isSelected();
	}

	public static void setDespuesEspacio(String aux) {
		jTextField9.setText(aux);
	}

	public static String getDespuesEspacioDato() {
		return jTextField9.getText();
	}

	public static void setDespuesEspacioTipo(String aux) {
		String ooo;
		for (int i = 0; i < jComboBox6.getItemCount(); i++) {
			ooo = jComboBox6.getItemAt(i).toString();
			if (jComboBox6.getItemAt(i).toString().contains(aux.toLowerCase())) {
				jComboBox6.setSelectedIndex(i);
			}
		}
	}

	public static String getDespuesEspacioTipo() {
		return (String) jComboBox6.getSelectedItem();
	}

	public static void setDespuesTiempo(boolean aux) {
		jCheckBox10.setSelected(aux);
	}

	public static boolean getDespuesTiempo() {
		return jCheckBox10.isSelected();
	}

	public static void getDespuesTiempo(String aux) {
		jTextField10.setText(aux);
	}

	public static void setDespuesTiempo(String aux) {
		jTextField10.setText(aux);
	}

	public static String getDespuesTiempoDato() {
		return jTextField10.getText();
	}

	public static void setDespuesTiempoTipo(String aux) {
		String ooo;
		for (int i = 0; i < jComboBox7.getItemCount(); i++) {
			ooo = jComboBox7.getItemAt(i).toString();
			if (jComboBox7.getItemAt(i).toString().contains(aux.toLowerCase())) {
				jComboBox7.setSelectedIndex(i);
			}
		}
	}

	public static String getDespuesTiempoTipo() {
		return (String) jComboBox7.getSelectedItem();
	}

	public void rep() {
		this.repaint();
	}

	// Declaración de varibales -no modificar
	//    private javax.swing.JButton jButton1;
	//    private javax.swing.JButton jButton2;
	//    private javax.swing.JButton jButton3;
	private static javax.swing.JButton jButton4;

	//    private javax.swing.JButton jButton5;
	//    private javax.swing.JButton jButton6;
	
	//private static javax.swing.JButton jButton7;
	
	private static javax.swing.JCheckBox jCheckBox1;

	private static javax.swing.JCheckBox jCheckBox10;

	private static javax.swing.JCheckBox jCheckBox2;

	private static javax.swing.JCheckBox jCheckBox3;

	private static javax.swing.JCheckBox jCheckBox4;

	private static javax.swing.JCheckBox jCheckBox5;

	private static javax.swing.JCheckBox jCheckBox6;

	private static javax.swing.JCheckBox jCheckBox7;

	private static javax.swing.JCheckBox jCheckBox8;

	private static javax.swing.JCheckBox jCheckBox9;

	private static javax.swing.JComboBox jCBAux;
	
	private static javax.swing.JComboBox jComboBox1;

	private static javax.swing.JComboBox jComboBox2;

	private static javax.swing.JComboBox jComboBox3;

	private static javax.swing.JComboBox jComboBox4;

	private static javax.swing.JComboBox jComboBox5;

	private static javax.swing.JComboBox jComboBox6;

	private static javax.swing.JComboBox jComboBox7;

	private static javax.swing.JLabel jLabel1;

	private static javax.swing.JLabel jLabel2;

	private static javax.swing.JLabel jLabel3;

	private static javax.swing.JLabel jLabel4;

	private static javax.swing.JLabel jLabel5;

	private static javax.swing.JLabel jLabel6;

	private static javax.swing.JLabel jLabel7;

	private static javax.swing.JLabel jLabel8;

	private static javax.swing.JLabel jLabel9;

	private static javax.swing.JPanel jPanel1;

	private static javax.swing.JPanel jPanel2;

	private static javax.swing.JPanel jPanel3;

	private static javax.swing.JPanel jPanel4;

	private static javax.swing.JPanel jPanel5;

	private static javax.swing.JPanel jPanel6;

	private static javax.swing.JPanel jPanel7;

	private static javax.swing.JPanel jPanel8;

	private static javax.swing.JPanel jPanel9;

	private static javax.swing.JTextField jTextField1;

	private static javax.swing.JTextField jTextField10;

	private static javax.swing.JTextField jTextField2;

	private static javax.swing.JTextField jTextField3;

	private static javax.swing.JTextField jTextField4;

	private static javax.swing.JTextField jTextField5;

	private static javax.swing.JTextField jTextField6;

	private static javax.swing.JTextField jTextField7;

	private static javax.swing.JTextField jTextField8;

	private static javax.swing.JTextField jTextField9;
	
	private static javax.swing.JTextField jTextField11;
	// Fin de declaración de variables

}