/*
 * SelectColor.java
 * 
 * Created on 24 de noviembre de 2004, 10:46
 */

package presentacion.visualizarCaptura;

import java.awt.*;
import javax.swing.event.*;
import javax.swing.table.AbstractTableModel;

/**
 * Establece el color de una fila seleccionada
 * 
 * @author Leonardo García & Jose Ramón Gutierrez
 * @version 2.0
 *  
 * @see TablePane
 */
public class SelectColor extends javax.swing.JFrame {
	/** * Color. */
	protected Color newColor;
	/** * Tablar de paquetes. */
	private TablePane RTablePane;

	/**
	 * Constructor por defecto de la clase.
	 * 
	 * @param RTablePane tabla de paquetes
	 */
	public SelectColor(TablePane RTablePane) {
		super("Seleccion de Color");
		this.RTablePane = RTablePane;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {
		jColorChooser1 = new javax.swing.JColorChooser();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		getContentPane().setLayout(
				new org.netbeans.lib.awtextra.AbsoluteLayout());

		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				exitForm(evt);
			}
		});

		jColorChooser1.getSelectionModel().addChangeListener(
				new ChangeListener() {
					public void stateChanged(ChangeEvent evt) {
						newColor = jColorChooser1.getColor();
					}
				});

		getContentPane().add(
				jColorChooser1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410,
						270));

		jButton1.setText("Aceptar");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		getContentPane().add(
				jButton1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1,
						-1));

		jButton2.setText("Cancelar");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		getContentPane().add(
				jButton2,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1,
						-1));

		pack();
	}
	/**
	 * Click al Cancelar. 
	 * 
	 * @param evt evento
	 */
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}
	/**
	 * click al Acpetar
	 * @param evt evento
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

		RTablePane.obtenercolor(newColor);

		this.dispose();
	}

	/**
	 * Al cerrar el formulario
	 * 
	 * @param evt
	 */
	private void exitForm(java.awt.event.WindowEvent evt) {
		this.dispose();
	}

	/** * Botón Aceptar. */
	private javax.swing.JButton jButton1;
	/** * Boton salir. */
	private javax.swing.JButton jButton2;
	/** * Seleccionar el color. */
	private javax.swing.JColorChooser jColorChooser1;
	// End of variables declaration

}